- src/svgeditor/tools/BitmapPencilTool.as
The bitmap-mode eraser tool is now 4x larger than it used to be.
> Scale the eraser up to make it easier to use

- src/ui/SpriteThumbnail.as
- src/ui/parts/LibraryPart.as
The background color for the sprite library is now grey to contrast with the white tiles.
> Added white background to sprite thumbnails.

- src/render3d/DisplayObjectContainerIn3D.as
> Now masking watchers properly in 3D

- src/sound/ScratchSoundPlayer.as
This will fix a common error we're seeing.
> Added null check for donefunction.

- src/primitives/MotionAndPenPrims.as
- src/render3d/DisplayObjectContainerIn3D.as
- src/scratch/ScratchObj.as
Fixes two major 3d bugs and a few minor primitive bugs due to missing null checks.
> Fix 3d issues 

- src/ui/parts/SoundsPart.as
> Fix sound tab list jumping to top when selecting sound

- src/scratch/ScratchRuntime.as
This drastically improves performance with many clones.
> No longer creating closures with every call to startEdgeTriggeredHats.

- src/svgeditor/BitmapEdit.as
- src/ui/parts/ImagesPart.as
> Disabled crop button unless there is a selection in the bitmap editor.

- src/ui/parts/ImagesPart.as
> The top-right image editing buttons are now anchored.

- src/Scratch.as
- src/scratch/ScratchRuntime.as
Most people do not actually care about file suffixes so why not just have one file filter with both suffixes?
> Only have one FileFilter containing both suffixes (.sb and .sb2)

- src/Scratch.as
- src/ui/parts/ImagesPart.as
- src/ui/parts/ScriptsPart.as
- src/util/ProjectIO.as
This makes it easier to inherit from these classes in derivative builds. Also, I noticed that there are some problems with overriding the ScratchStage() implementation uniformly - this fixes that as well (565810a7d085522da6b0ff8b6b0504fc81606cb9).
> Refactor imagespart scriptspart

- src/primitives/Primitives.as
> Added type check for random block

- src/scratch/ScratchStage.as
This causes issues in the offline editor because fromBackpack doesn't exist on MediaInfo objects.
> Removed logic for handling items from the backpack

- src/util/GestureHandler.as
> Don't allow drags to start while a project is loading.

- src/scratch/ScratchSound.as
- src/sound/WAVFile.as
> Added mono and double precision support.

- src/scratch/ScratchStage.as
Note that this PR should be merged only after #813 is merged.
> Fix issue 788

- src/render3d/DisplayObjectContainerIn3D.as
- src/render3d/shaders/fragment.agal
Note that this PR should be merged only after #813 is merged.
> Fix issue 769

- src/util/ProjectIO.as
Fix for https://github.com/LLK/scratch-flash-online/issues/168
> Don't try to decode zero length ByteArrays.

- src/primitives/Primitives.as
> Avoid AS3 class properties when caching lower case strings

- src/util/Server.as
These are remnants from the ScratchX merge.
- We now try to reload crossdomain.xml in the event of a security error.
- During a whenDone(null) call which is reporting an error,
Server.callServerErrorInfo contains information about the attempt.
> Merged ServerOnline.callServer() features upward

- src/scratch/ScratchCostume.as
> Calculate MD5 if it's null

- src/Scratch.as
- src/ui/parts/TopBarPart.as
- src/util/Server.as
Fix logo position problems from ScratchX merge and a build problem for the offline editor
> Fix logo positioning

- src/Scratch.as
- src/ui/parts/LibraryPart.as
- src/ui/parts/ScriptsPart.as
- src/uiwidgets/SimpleTooltips.as
This adds a new layout mode for the interest based pathways research project. It's not done but it's good enough for the rest of the team to use in their design iterations.
> Microworlds

- src/scratch/ScratchSound.as
- src/sound/ScratchSoundPlayer.as
We found a few issues and there isn't enough time to resolve them before the deploy.
> Revert sound refactor

- src/primitives/Primitives.as
Fixes https://github.com/LLK/scratch-flash/issues/857
I tested 1/0 == 'Infinity' (true) and '' > 0 (false)
> Fix argument comparisons

- src/sound/WAVFile.as
Fixes https://github.com/LLK/scratch-flash/issues/844
> Added a null check in imaDecompress.

- src/scratch/ScratchRuntime.as
Don't update the palette if nothing changed. Fixes https://github.com/LLK/scratch-flash/issues/798.
> Optimize toggling watcher visibility

- src/primitives/SensingPrims.as
- src/scratch/BlockMenus.as
- src/scratch/ScratchRuntime.as
> Add "any" to key press menu

- src/blocks/Block.as
- src/scratch/BlockMenus.as
- src/scratch/ScratchRuntime.as
Renaming broadcasts not allowing already existing broadcast messages.
> Renaming broadcasts (using right click menu)

- src/soundedit/WaveformView.as
This should resolve an exception we're seeing in playBuffer (RangeError: Error #1125).
> Don't play beyond the end of our buffer

- src/ui/parts/ImagesPart.as
Users seem to be trying to import animated GIFs into costumes about 100 times per day and causing errors.
> Support importing animated GIFs into a costume

- src/extensions/ScratchExtension.as
- src/util/Server.as
> Extension URL fixes

- src/scratch/BlockMenus.as
- src/scratch/ScratchRuntime.as
> Simple, orthogonal fixes for #810, #815 and #831.

- src/blocks/Block.as
- src/scratch/BlockMenus.as
Prevents exceptions when a broadcast contains an expression.
> Fix #968 - don't assume args for broadcast will be BlockArg.

- src/Scratch.as
To test: shift-click File menu and select "Show version details"
IDEA builds will report "dev"; Ant and Gradle builds should show a unique identifier for the commit(s) used to create the build.
> Add "Version Details" dialog to shift-File menu

- src/svgeditor/tools/BitmapBackgroundTool.as
-There were some problems with handling click events
-The as3 mouse events look at where the mouse ends up, which makes
some problems
-This is now tracked manually where necessary
>     Fixed segmentation undo/redo bugs

- src/svgeditor/tools/BitmapBackgroundTool.as
-Do an "undoable" save when user clicks away
-Left the option on the commitMask method because
a redo option may need to apply a mask but should not
create an additional undo/redo record
> Applying mask should trigger save

- src/svgeditor/DrawPropertyUI.as
- src/svgeditor/tools/BitmapBackgroundTool.as
-Prevent bottom and right edges of the bounding rect
from going beyond the edges of the working area bitmap
-Fixes #257 which was resulting in error 2030 (EOF) when
the rectangle exceeded the edges of the bitmap
> Fixed #257 segmentation bounding rect bug

- src/svgeditor/tools/BitmapBackgroundTool.as
-cropRect could possible have a dimension of 0.
Now the minimum dimension is SEGMENT_STROKE_WIDTH
-backdrops should have their backgrounds set to opaque
white rather than transparent black
> Two bug fixes for segmentation tool

- src/Specs.as
- src/blocks/Block.as
- src/blocks/BlockIO.as
- src/primitives/MotionAndPenPrims.as
- src/scratch/BlockMenus.as
- src/scratch/ScratchRuntime.as
- src/scratch/ScratchStage.as
- src/uiwidgets/ScriptsPane.as
-required creation of new 'location' menu, since the existing menu
was used in a couple places
> Added go to random position block

- src/scratch/BlockMenus.as
- src/scratch/ScratchObj.as
- src/scratch/ScratchRuntime.as
- src/scratch/ScratchSprite.as
Fixes LLK/scratch-flash-online#245
> Translate default sprite and message names

- src/primitives/LooksPrims.as
(More like numerical costume names do in 'switch costume' menu.)
Simple fix for issue #1013.
> Makes numerical backdrop names in 'switch backdrop' menu behave better.

- src/scratch/ScratchSound.as
These were accidentally removed in an overly-aggressive cleanup pass...
> Restore JSON functions
