LLK/scratch-flash

- src/Scratch.as
When viewing a project on https://scratch.mit.edu/, the project editor is in the space where the player should be, and see inside is broken:
This has been reported multiple times on the forums, and checking for both HTTP and HTTPS when determining whether to default to the player or not should fix the problem.
> Check for HTTPS also when determining if offline

- src/Scratch.as
This fixes an issue where recently added bitmap sprites appear invisible when the 3d renderer is in use.
> Force an update to the 3d renderer when a sprite is added to the stage.

- src/svgeditor/DrawProperties.as
- src/svgeditor/DrawPropertyUI.as
- src/svgeditor/ImageEdit.as
- src/svgeditor/tools/BitmapPencilTool.as
- src/svgeditor/tools/EraserTool.as
The default eraser size is larger than the default pen size, but the limits are currently the same.
This fixes #596
> Store eraser width separately from pen width

- src/uiwidgets/DialogBox.as
When the user presses ESC in a dialog, cancel is called.
> ESC in a dialogs

- src/scratch/ScratchComment.as
- src/uiwidgets/ScriptsPane.as
When the user adds a comment to a block, it would be convenient to have the text "add comment here..." selected and the TextField focused.
> Automatically select text when adding comment

- src/scratch/BlockMenus.as
When a user defined block has been edited, and some inputs has been added/removed, the width of the block can change, so we need to call fixCommentLayout.
> Comment layout fix

- src/ui/parts/base/BaseScriptsPart.as
- src/uiwidgets/ScrollFrame.as
Most ScrollFrames are OK with catching the drag event from a child, so
move the code that prevents that into the scripts part. Any other scroll
frame that wants to prevent it can follow this pattern.
> Move scroll gesture pickiness to the scripts area

- src/Scratch.as
- src/scratch/ScratchCostume.as
This change fixes a crash that can sometimes happen while converting a vector costume into a bitmap costume. The fix is different depending on whether Scratch is running a newer or older version of Flash.
The problem stems from changing the stage quality when rendering the SVG into a bitmap. Changing the stage quality sometimes -- but not always -- fires a 'resize' event that is caught in Scratch.as, causing the image editor to be shut down in the middle of the conversion. The actual crash happens inside BitmapEdit's saveToCostume() method, where targetCostume is unexpectedly null.
On newer versions of Flash we now use drawWithQuality() to avoid the need to change the stage's quality.
On older versions of Flash we now set a flag to suppress the resize event, and clear that flag after the …
> Convert to bitmap crash fix

- src/primitives/SensingPrims.as
> The distance to a non-existent sprite is now 10000 (was 0).

- src/scratch/ScratchCostume.as
- src/ui/media/MediaLibrary.as
- src/util/IServer.as
- src/util/ProjectIO.as
- src/util/Server.as
Use separate files for sprites, costumes, backdrops, and sounds. This makes them load faster and the costume library is now generated from the sprite library.
> Media library refactor

- src/Specs.as
Adding ? at the end of <list contains> block to make it consistent with other boolean blocks
Fixes #621 
##TestCases : 
1. Make sure <list contains> block works as expected
2. Make sure the other blocks look ok
> #621 Adding ? At the End Of List Contains Block

- src/IRenderIn3D.as
- src/render3d/DisplayObjectContainerIn3D.as
- src/render3d/SpriteStamp.as
- src/scratch/ScratchObj.as
- src/scratch/ScratchSprite.as
- src/scratch/ScratchStage.as
This is a continuation of the fix made for https://github.com/LLK/scratch-flash/issues/685.
> Removed unused methods in interface. Cleaned up and optimized stamping.

- src/primitives/MotionAndPenPrims.as
When penDown is called, draw a tiny circle instead of a diagonal line. Fixes #482.
> Fix pen touches

- src/blocks/Block.as
- src/blocks/BlockArg.as
- src/primitives/Primitives.as
This removes the code that added epsilon (1 / 4294967296) to integer block arguments that contained a decimal point. This caused issues with 'ceiling' and comparing values (0.0 != 0).
There were ways to implement this that would not perform well or would increase memory usage. I think I found a good way to fix this while maintaining performance and memory usage.
Fixes #582
> Fix integer processing

- src/scratch/ScratchStage.as
Add a tiny number to the stage's ghost effect when the video is on and semi-transparent. This ensures that a shader with ghosting (alpha altering) is used by the stage.
Fixes #679
> Fix video transparency in 3D mode

- src/primitives/MotionAndPenPrims.as
Now supporting pen alpha when the pen color format is ARGB and A (alpha) is greater than zero. This means you can have a semi-transparent pen stroke but you cannot have an invisible pen stroke. This is to provide backward compatibility to projects setting the pen color but not the alpha value.
Addresses #730
> Added support for pen alpha

- src/Scratch.as
- src/svgeditor/tools/BitmapPencilTool.as
- src/svgeditor/tools/EraserTool.as
- src/svgeditor/tools/EyeDropperTool.as
- src/svgeditor/tools/ObjectTransformer.as
- src/svgeditor/tools/PaintBrushTool.as
- src/svgeditor/tools/PathAnchorPoint.as
- src/svgeditor/tools/PathTool.as
- src/svgeditor/tools/SVGCreateTool.as
- src/svgeditor/tools/SVGTool.as
- src/svgeditor/tools/TextTool.as
Fixes an null reference error we've been seeing in the editor. Here is how you can cause it to happen before this change: create new project, click on icon to create a new sprite (paint brush icon), switch to scripts tab, click on help (?) at the top.
Here is the stack trace:
Error #1009 Root Cause
(Unknown file) ? in svgeditor.tools::BitmapPencilTool/shutdown()
(Unknown file) ? in svgeditor.tools::SVGTool/removedFromStage()
(Unknown file) ? in svgeditor::ImageEdit/setToolMode()
(Unknown file) ? in svgeditor::BitmapEdit/setToolMode()
(Unknown file) ? in svgeditor::ImageEdit/enableTools()
(Unknown file) ? in Scratch/enableEditorTools()
(Unknown file) ? in uiwidgets::CursorTool$/setTool()
(Unknown file) ? in MethodInfo-1176()
(Unknown file) ? in uiwidgets::IconButton/mouseDown()
> Fix null stage refs in paint editor by adding a static var for the stage

- src/scratch/ScratchRuntime.as
Fixes an issue we're seeing with the WeDo in workshops.
> Call resetPlugin before installing project or loading extensions.

- src/render3d/DisplayObjectContainerIn3D.as
Fixes an exception that sometimes occurs when ScratchSprite.bitmap() is called and 3d rendering is enabled.
Call stack:
(Unknown file) ? in render3d::DisplayObjectContainerIn3D/uploadBuffers()
(Unknown file) ? in render3d::DisplayObjectContainerIn3D/getRenderedChild()
(Unknown file) ? in scratch::ScratchSprite/bitmap()
(Unknown file) ? in scratch::ScratchSprite/bounds()
(Unknown file) ? in scratch::ScratchSprite/hitTestPoint()
(Unknown file) ? in util::GestureHandler/findMouseTargetOnStage()
(Unknown file) ? in util::GestureHandler/findMouseTarget()
(Unknown file) ? in util::GestureHandler/mouseDown()
> Always check the buffers when rendering an individual child.

- src/uiwidgets/ScriptsPane.as
When dragging a block from the scripts palette to the scripts panel, insertion/wrapping previews will only occur when the mouse is inside the scripts panel.
This issue is reported in https://github.com/LLK/scratch-flash/issues/727
> Fixing issue 727

- src/scratch/PaletteBuilder.as
Shift extension LED left so not partly obscured by vertical scrollbar with extensions with many commands.
> Move extension LED left

- src/extensions/ExtensionManager.as
Internal extensions should only hide/show blocks, not be permanently deleted, as this stops add-remove-add of that extension from working.
> Do not permanently delete internal extensions

- src/render3d/DisplayObjectContainerIn3D.as
I had removed the argument since pre-multiplied alpha lets us use the same blend mode for both stamps and normal drawing, making for simpler code. However, blending is cheaper when the destination factor is zero. With that in mind it may be a better idea to turn off blending when we can, especially on mobile platforms.
Also, disable error checking on Context3D. I left the line in there so it's easy to change it to `true` when debugging.
> 3d cleanup

- src/ui/media/MediaLibrary.as
The backdrop JSON can optionally specify the bitmap resolution to use
for a given backdrop. Previously this setting ws ignored on backdrops
and would even prevent the detection of a high-resolution backdrop. Now
it is honored if present, and if absent then the automatic resolution
detection still works.
Fixes #672 (again).
> Honor resolution setting if present in JSON

- src/util/Server.as
Necessary to fix the online scratch version after merging ScratchX.
> Added a method for setting default urls that can be overridden.

- src/util/Server.as
If the SWF is loaded over HTTP or HTTPS then overrideURLs will replace the protocol specified by the incoming URLs with a protocol matching the SWF's URL. If the SWF was not loaded over HTTP or HTTPS then overrideURLs will not modify the incoming URLs.
This is effectively the same behavior that the online editor used before the ScratchX merge.
> Override protocols in URL overrides

- src/render3d/DisplayObjectContainerIn3D.as
- src/scratch/ScratchStage.as
The previous method of making the video image transparent relied on the fact that all objects were drawn with the same shader, and allowed the video image's alpha value to be used in place of the ghost effect. This broke when we started determining the shader on a per-object basis. Now video transparency is implemented by applying the standard ghost effect to the bitmap object representing the video image.
This fixes LLK/scratch-flash#837 and LLK/scratch-flash#838
See issues for test cases
> Apply video transparency as ghost effect

- src/render3d/DisplayObjectContainerIn3D.as
Instead of calling `setRenderView()` when setting up the 3D context, call `onStageResize()` which calls `setRenderView()` after calculating `appScale` and collecting the UI transform.
Test case: see issue #845
> Ensure correct appScale when activating 3D mode

- src/scratch/TalkBubble.as
- src/uiwidgets/ResizeableFrame.as
This improves the quality of rounded corners in list and variable watchers:
Before/after:
as well as talk bubbles:
Before/after:
> Fix corner rounding

- src/scratch/BlockMenus.as
(It would also be nice if the text was selected, but it seems like it can be when deployed, judging from the code comment in DialogBox.showOnStage).
> When renaming a variable, the current name is proposed.

- src/Scratch.as
- src/util/GestureHandler.as
This change will add the function of aborting a drag operation by pressing ESC. That will restore the position/insertion of the block to the place it were when the drag operation was initiated.
> Aborting block drag operations by pressing ESC.

- src/scratch/BlockMenus.as
Puts the 'any' before the letter keys and after the arrow keys. Moves 'space' to the top.
> Moved any key in menu

- src/ui/media/MediaLibrary.as
Fixes https://github.com/LLK/scratch-flash-online/issues/168
> Don't thrown an exception when loadBytes fails.

- src/scratch/PaletteBuilder.as
The button only works on ScratchX so it should be hidden elsewhere.
This fixes LLK/scratch-flash-online#186
> Show Load Experimental Extension only in dev mode

- src/scratch/ScratchRuntime.as
When 'any' key support went in, this code was rearranged so that checking `stack.args[0]` was no longer protected by the `stack.op` check through short-circuiting. This change makes the `stack.op` check happen first again, accessing `stack.args` only if that check passes.
This fixes #880
> Fix exception when processing `key () pressed?`

- src/render3d/DisplayObjectContainerIn3D.as
Fixes an exception we're seeing.
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3D.html#configureBackBuffer() - "The minimum size of the buffer is 32x32 pixels."
> Make sure the backbuffer isn't too small

- src/render3d/DisplayObjectContainerIn3D.as
This gives slightly less overall texture memory and uses smaller textures. Currently our top exception is from trying to use textures that are too big and unsupported by the user's system.
The exception is ArgumentError: Error #3683: Texture too big (max is 2048x2048).
> Bump down the max texture size.

- src/scratch/ScratchCostume.as
This should fix an exception we're seeing in ScratchCostume::computeTextLayer (TypeError: Error #2007).
> add null check

- src/extensions/ExtensionManager.as
This change requires https://github.com/LLK/scratchr2/pull/2757
The `stop()` method is a new method that will allow ScratchExtensions to
decide whether to call the new `_stop()` method or the old `resetAll()`
method on a per-extension basis.
> Make stop button call ScratchExtensions.stop()

- src/svgeditor/tools/PathAnchorPoint.as
If the instance has been removed from the stage then this.stage will be null. Use the app's stage to avoid a null stage value.
> Use app's stage instead

- src/Scratch.as
We were setting the `color` property on the stage with the assumption that it would fail silently on versions of Flash which didn't support that feature. Unfortunately on Linux this throws an exception. This change checks for the property before trying to set it.
This fixes LLK/scratch-flash-offline#80
> Set stage color only if supported

- src/interpreter/Interpreter.as
This occurs when there is a timer hat block which can run before the green flag is pressed.
> Fix error when primVarGet is called without an active thread.

- src/render3d/DisplayObjectContainerIn3D.as
When in 2D, doing a `touching color` test while a sprite is partially off the stage tests against solid white. This change implements the same behavior in 3D, where previously the region would be transparent black.
This is a partial fix for #850.
> Fill off-stage areas with white for touch test

- src/ui/parts/ImagesPart.as
If we notice that all of the pixels of the bitmap are transparent then there's no need to add a bitmap element to the SVG.
This fixes #415
> Skip empty bitmap element Bitmap-to-Vector convert

- src/scratch/BlockMenus.as
- src/scratch/PaletteBuilder.as
The 'clean up' and 'when Stage clicked' strings are now available for translation.
This fixes LLK/scratchr2#2785
> Make two more strings available for translation

- src/ui/media/MediaLibrary.as
This avoids throwing an exception when attempting to read a very short file, such as a zero-byte file.
This fixes LLK/scratch-flash-online#102
> Check length before magic on sprite/costume upload

- src/Scratch.as
This was using the wrong call and causing these errors to be logged as `err` with the actual message stored in the `extraData` field.
This fixes LLK/scratch-flash-online#211
> Fix the way jsThrowError logs its message

- src/translation/TranslatableStrings.as
- src/uiwidgets/ScriptsPane.as
The 'clean up' string was not being included in the editor exports, so
I've added it here explicitly. The 'add a comment' string was already
included in the editor exports, but I can't figure out why... it seems
best to properly include it here as well.
> Add strings() method to ScriptsPane

- src/logging/Log.as
- src/translation/Translator.as
Logging events forwarded to the JS console now include extradata.
The `currentLang` is set in Translator.as before checking for translation problems instead of after.
When a warning is logged due to a block argument mismatch, the current language is included in the event.
> Improve logging, especially for translation errors

- src/Scratch.as
We're getting a lot of error events from this, especially for "Calling JSeditorReady() failed." Changing these messages to warnings will prevent us from getting error events for what looks like a symptom rather than the actual cause. The warnings will still appear in the log for an error that happens afterward.
> Log `jsThrowError()` as a warning

- src/logging/Log.as
- src/util/JSON.as
- src/util/Server.as
- Logging events echoed to JS now have their `extraData` sent over
intact, so that the objects can be inspected in the JS debugger.
- JSON stringification of event `extraData` is protected with a
try/catch, in case some non-stringifiable data sneaks in. If
stringification throws the `extraData` will be replaced with a string
indicating such.
- JSON stringification has been extended to handle `ByteArray` as if it
were a string. This probably isn't useful except for logging, but it
does prevent an exception from being thrown.
- The logging for `callServer` has been simplified and uncommented. It
had originally been commented out in order to avoid overloading our
event tracking system. That's still a concern, but now it can be
logged as a warning: it won't generate a tracking event, but it …
> Make JS log events richer; improve callServer logs

- src/interpreter/Interpreter.as
This fix means currentDoObj gets used for numerous other primitives that can also have their blocks end up in a hat block (where activeThread is invalid) - just as primVarGet uses currentDoObj in #913 to fix #912 & #468.
For a demo of the bug, see https://scratch.mit.edu/projects/90835029/
> Fix #966 by using currentDoObj in Interpreter.targetObj() & targetSprite()

- src/svgeditor/ImageEdit.as
-The listener in question was added with useCapture=true
-When an SVG element is ungrouped, it will be the target of the
MOUSE_DOWN event
-Now, check if the element I'm clicking on would make a non-group
Selection.  If so, add a listener with useCapture=false
> Fixed SVG grow/shrink problem

- src/blocks/Block.as
The `collectArgs()` function runs when anything changes in the arguments of a block or any of its descendants, recursively. If this is called on a Requester block which currently has a value, reset / discard that value in case it's no longer valid given the argument change.
This resolves LLK/scratchx#61
> Reset requester state when args might have changed

- src/scratch/ScratchCostume.as
-As a catch all, you must be able to make a valid XML object from
the (potentially) SVG data
-Adding this to isSVGData seems to engage the preexisting error
handling functionality
> Added valid XML check to SVG decoding

- src/scratch/PaletteBuilder.as
- src/ui/PaletteSelector.as
The string "when Stage clicked" was showing up in the "UI" strings export (the "Scratch Editor" project in Pootle) instead of the "commands" export (the "Scratch Blocks" project in Pootle). This change fixes that, resolving #1031.
Note that this only affects string export, so it doesn't need to be deployed to take effect. Translators will see the change as soon as the exported files are imported into Pootle.
> Move 'when Stage clicked' to blocks strings

- src/blocks/Block.as
- src/extensions/ExtensionManager.as
- src/scratch/PaletteBuilder.as
In the offline editor, reporters must be treated as requesters. This had been implemented by converting `'r'` blocks into `'rR'` blocks, but this ended up "leaking" into SB2s saved from the offline editor, which in turn caused problems with the online editor.
Now, the `Block` constructor calls the new `shouldForceAsync()` method on `ExtensionManager` to determine whether or not to set `forceAsync` (renamed from `forceRequester`). The block type/spec is never altered.
In support of this change, the logic for showing the watcher checkbox was updated to base its decision on the constructed block rather than the block spec.
I tried to keep #1032 in mind while making this change; my hope is that this technique will work well there, too.
This resolves #1051
> Eliminate 'rR' block type hack

- src/extensions/ExtensionManager.as
After recent changes to extension loading and the `resetPlugin()` sequence, HTTP extensions are no longer reliably loaded early enough to avoid the need to update their blocks afterward. Calling `translationChanged()` calls `updateScriptsAfterTranslation()` on each object, replacing red error blocks with proper extension blocks.
This resolves #1058
> Fix up blocks after loading HTTP extension

- src/blocks/Block.as
- src/extensions/ExtensionManager.as
A block should only be `forceAsync` if the block is from a JS extension and running in a context where the JS interface is async. Currently the only such context is the offline editor.
Built-in blocks and HTTP extension blocks should never `forceAsync`.
This resolves #1066 and a variety of other issues.
> Fix `forceAsync` logic

- src/translation/Translator.as
I find the issue "Default Chinese Character Font Size Larger #875" hasn't been solved. Because the code change doesn't worked .
The reason that it failed is because the files in the locale folder . We have 2 po files for chinese (zh_CN.po zh-cn.po ) and 2 po files for taiwanese (zh_TW.po zh-tw.po) . So I fixed the array to include all these 4 files.
Also the size of the font is still not big enough. So I increase font size a little bit.
I built it in my machine and it worked ! Hope the code could help students in chinese and taiwan for learning Scratch. #875
> fix chinese font size been too small. (fix  issue #875)

- src/extensions/ExtensionManager.as
This resolves #1128
Testing:
- Download each of these projects, renaming the files to `*.sbx`
- [forbidden.zip](https://github.com/LLK/scratch-flash/files/303627/forbidden.zip)
- [mesh@github.zip](https://github.com/LLK/scratch-flash/files/303628/mesh.github.zip)
- Load each project.
Expected results:
- `mesh@github.sbx` attempts to load an extension hosted on `github.io`, which should succeed: you should see the Mesh blocks in the "More Blocks" category.
- `forbidden.sbx` attempts to load an extension hosted on `forbidden.url`, which should fail in the console with the error message below.
Note that, since the site `forbidden.url` doesn't exist, the "forbidden" extension will always fail to load. Testing should only pass if the message below appears in the JS console.
> Refusing to load …
> Allow experimental extensions from coding.me

- src/util/GestureHandler.as
Previous behavior: drag-scrolling was generally allowed, except on `ScriptPane` targets. This prevented horizontal drag-scrolling in the block palette as desired, but unfortunately also prevented vertical drag-scrolling in the block palette and all drag-scrolling in the scripting area. It also allowed a slight "wiggle" in a few places, such as the costume list.
New behavior: horizontal drag-scrolling is allowed on any target which allows horizontal scrollbars, and vertical drag-scrolling is allowed on any target which allows vertical scrollbars. These are checked independently: areas like the sprite list, costume list, or block palette can drag-scroll vertically but not horizontally.
This is another attempt to fix #742.
See also #1080, which is not addressed by this change.
Testing:
- …
> Allow drag-scroll iff scrollbars allowed, per axis

- scratch.gradle
This shouldn't have any noticeable impact on the editor, and I haven't noticed anything in my testing, but we should consider giving the editor a more thorough check than usual before deploying this build.
This resolves #1195
> Updgrade Gradle builds to apache-flex-sdk 4.15.0

- src/watchers/ListWatcher.as
The `ListWatcher` class creates a cell for each visible item as part of its resize handling (see `updateContents`). This can take a long time if the height of the list watcher and the length of its list are both very large. This is especially true at load-time, when a list watcher may not yet know what its true size should be.
This change enforces bounds in the `setWidthHeight()` method of the `ListWatcher` class. Bounding the size effectively bounds the number of list cells that will be created, eliminating long load-time delays.
This resolves #1223
> Enforce bounds in ListWatcher's setWidthHeight()

- src/util/Server.as
Flash doesn't correctly handle a POST with an empty body: the URL
handler automatically converts the POST into a GET. This causes a 403
leading the editor to think the user has logged out. The end result is a
save failure that's to recover from.
A project shouldn't have a zero-length asset anyway, but if it does get
into that situation then this change will prevent the entire project
from being "lost" due to a single-asset error.
This resolves #1232 
Testing (see also https://github.com/LLK/scratch-flash/issues/1232#issuecomment-263382635):
1. Download [empty-POST.sb2.zip](https://github.com/LLK/scratch-flash/files/625870/empty-POST.sb2.zip) and optionally rename it to just "empty-POST.sb2"
2. Go to Scratch with a project you don't mind replacing (new project is fine)
3. Click "File" then …
> Skip POSTs with empty body, output a warning

- src/Scratch.as
When loading a project from a file, remove all instances of '.sb', '.sb2', or '.sbx' found at the end of the file name. Repeat until none remain.
Previous behavior: remove either '.sb' or '.sb2' exactly once. Since this didn't include '.sbx' there are now projects with titles like 'Silly.sbx.sbx.sbx' -- this was the motivation for making this check repeat.
Testing:
- Make sure the projects gets an appropriate title after loading various project files from local disk. For example, all of the following should result in a project title of "Example":
This resolves LLK/scratchx#32
> Remove all file extensions when loading a project

- src/Scratch.as
- src/translation/Translator.as
Previous behavior: Always list English first, then append the languages retrieved from the server. If English is also in that list, then English will be listed twice.
New behavior: Use the language list retrieved from the `lang_list.txt` file exactly. If we fail to load that file, use English as a fallback.
Note that this will affect both the online and offline versions of the editor as well as ScratchX.
This resolves #1210
> Don't list English twice in the language selector

- src/util/Server.as
HTTP/2 requires all header field names to be expressed in lowercase.
See LLK/scratch-www#1152. Since this may end up being a high-priority issue, I'd like to consider treating this as part of the January 19th milestone.
/cc @colbygk @jwzimmer
> HTTP/2 compat: use lowercase header field names

- src/blocks/BlockIO.as
Before: `blockToArray` returns the parsed value of each block arg
After: `blockToArray` returns the raw text value of each block arg
This means that block arguments should now be preserved by block duplication or save/load cycles.
This resolves #1270
> Preserve user text for block args in blockToArray

- src/Specs.as
- src/extensions/ExtensionManager.as
- src/translation/TranslatableStrings.as
- src/translation/Translator.as
This change removes the hard-coded list of extension specs from `Specs.as`, replacing it with a function on `ExtensionManager` which reads block specs from the actual extensions. This requires the extensions to be loaded, so the function pops up a warning dialog if it detects that any built-in extension is not loaded.
This will be used to resolve LLK/scratchr2#4331
> Translation: ask extensions for their specs

- src/blocks/BlockIO.as
When a block arg's internal storage is a string, save that instead of the field text. This preserves the internal, universal values (like `'_mouse_'`) instead of the localized value (like `'mouse-pointer'` or `'puntero del ratón'`) for selections in drop-down menus.
This resolves LLK/scratch-flash-online#306 which was introduced by #1273
> Save block arg internal strings when available

- src/blocks/BlockIO.as
We've decided that the risk associated with these changes (along with #1287) outweighs the benefit. We'll try to make sure we get this right in Scratch 3.0 :)
> Revert #1278 and #1273

- src/primitives/SensingPrims.as
- src/scratch/ScratchRuntime.as
The `keyIsDown` array now tracks keys by their normalized `keyCode` rather than ASCII value. This means that in situations where we don't get a good `charCode` (see #1334) we can still track a key without worrying about mapping its `keyCode` to an ASCII value. That mapping is straightforward for some keys (letters, for example) but not for others (comma, for example).
This change is the result of a problem that @tarmelop noticed with #1341 where certain keys would work for the `when {any} key pressed` hat block but would not work for the `is {any} key pressed?` reporter. These are keys like the comma, where the `keyCode` value doesn't match the character's ASCII value -- this was the key oversight with #1341. Also, the `keyCode` value for some such keys is larger than 127, so that …
> Use `keyCode` instead of ASCII for `primKeyPressed`
